class Common():
    TITLE_FONT_STYLE = ('Calibri', 24)
    UTILITY_BUTTON_STYLE = ('Calibri', 14)
    UTILITY_BUTTON_GAP = 15
    note_ranges = [1,2,3,4,5,6,7,8,9,0]
    GENDER_BLADE_HEIGHT_BASE = 17
    GENDER_BLADE_WIDTH = 9
    DIVIDER_HEIGHT = 21
    DIVIDER_WIDTH = 7
    DIVIDER_GAP_HEIGHT = 100
    HOLDER_HEIGHT = 105
    HOLDER_WIDTH = 70
    NOTE_DISPLAY_WIDTH = 16
    NOTE_DISPLAY_HEIGHT = 12
    NOTES_DISPLAY_AND_SCROLLER_HEIGHT = 130
    NOTES_DISPLAY_CANVAS_HEIGHT = NOTES_DISPLAY_AND_SCROLLER_HEIGHT - 4
    NOTES_DISPLAY_CANVAS_WIDTH = 350

