class CommonWindows():
    TITLE_FONT_STYLE = ('Calibri', 24)
    UTILITY_BUTTON_STYLE = ('Calibri', 14)
    UTILITY_BUTTON_GAP = 20
    note_ranges = [1,2,3,4,5,6,7,8,9,0]
    GENDER_BLADE_HEIGHT_BASE = 17
    GENDER_BLADE_WIDTH = 10
    DIVIDER_HEIGHT = 30
    DIVIDER_WIDTH = 10
    DIVIDER_GAP_HEIGHT = 200
    HOLDER_HEIGHT = 150
    HOLDER_WIDTH = 100
    NOTE_DISPLAY_WIDTH = 20
    NOTE_DISPLAY_HEIGHT = 15
    NOTES_DISPLAY_AND_SCROLLER_HEIGHT = 160
    NOTES_DISPLAY_CANVAS_HEIGHT = NOTES_DISPLAY_AND_SCROLLER_HEIGHT - 4
    NOTES_DISPLAY_CANVAS_WIDTH = 500
